DROP TABLE IF EXISTS catalog_code;

CREATE TABLE catalog_code (
	code varchar(12) primary key,
	value varchar(255)
) Engine=InnoDB;

INSERT INTO catalog_code(code, value) values ('3C', 'Third Cambridge Catalog of Radio Wave Sources');
INSERT INTO catalog_code(code, value) values ('Abell', 'George Abell (planetary nebulae and galaxy clusters)');
INSERT INTO catalog_code(code, value) values ('ADS', 'Aitken Double Star catalog');
INSERT INTO catalog_code(code, value) values ('AM', 'Arp-Madore (globular clusters)');
INSERT INTO catalog_code(code, value) values ('Antalova', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('Ap', 'Apriamasvili (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('Arp', 'Halton Arp (interacting galaxies)');
INSERT INTO catalog_code(code, value) values ('Bark', 'Barkhatova (open clusters)');
INSERT INTO catalog_code(code, value) values ('B', 'Barnard (dark nebulae)');
INSERT INTO catalog_code(code, value) values ('Basel', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('BD', 'Bonner Durchmusterung (stars)');
INSERT INTO catalog_code(code, value) values ('Berk', 'Berkeley (open clusters)');
INSERT INTO catalog_code(code, value) values ('Be', 'Bernes (dark nebulae)');
INSERT INTO catalog_code(code, value) values ('Biur', 'Biurakan (open clusters)');
INSERT INTO catalog_code(code, value) values ('Blanco', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('Bochum', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('Ced', 'Cederblad (bright nebulae)');
INSERT INTO catalog_code(code, value) values ('CGCG', 'Catalog of Galaxies and Clusters of Galaxies');
INSERT INTO catalog_code(code, value) values ('Cr', 'Collinder (open clusters)');
INSERT INTO catalog_code(code, value) values ('Czernik', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('DDO', 'David Dunlap Observatory (dwarf galaxies)');
INSERT INTO catalog_code(code, value) values ('Do', 'Dolidze (open clusters)');
INSERT INTO catalog_code(code, value) values ('DoDz', 'Dolidze-Dzimselejsvili (open clusters)');
INSERT INTO catalog_code(code, value) values ('Dun', 'Dunlop (Southern objects of all types)');
INSERT INTO catalog_code(code, value) values ('ESO', 'European Southern Observatory (Southern objects)');
INSERT INTO catalog_code(code, value) values ('Fein', 'Feinstein (open clusters)');
INSERT INTO catalog_code(code, value) values ('Frolov', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('Gum', 'Bright nebulae');
INSERT INTO catalog_code(code, value) values ('H', 'William Herschel (globular clusters)');
INSERT INTO catalog_code(code, value) values ('Haffner', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('Harvard', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('Hav-Moffat', 'Havermeyer and Moffat (open clusters)');
INSERT INTO catalog_code(code, value) values ('He', 'Henize (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('Hogg', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('Ho', 'Holmberg (galaxies)');
INSERT INTO catalog_code(code, value) values ('HP', 'Haute Provence (globular clusters)');
INSERT INTO catalog_code(code, value) values ('Hu', 'Humason (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('IC', '1st and 2nd Index Catalogs to the NGC (All types of objects except dark nebulae)');
INSERT INTO catalog_code(code, value) values ('Isk', 'Iskudarian (open clusters)');
INSERT INTO catalog_code(code, value) values ('J', 'Jonckheere (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('K', 'Kohoutek (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('Kemble', 'Father Lucian Kemble (asterisms)');
INSERT INTO catalog_code(code, value) values ('King', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('Kr', 'Krasnogorskaja (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('Lac', 'Lacaille (globular clusters)');
INSERT INTO catalog_code(code, value) values ('Loden', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('LBN', 'Lynds (bright nebula)');
INSERT INTO catalog_code(code, value) values ('LDN', 'Lynds (dark nebulae)');
INSERT INTO catalog_code(code, value) values ('NPM1G', 'Northern Proper Motion, 1st part, Galaxies');
INSERT INTO catalog_code(code, value) values ('Lynga', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('M', 'Messier (all types of objects except dark nebula)');
INSERT INTO catalog_code(code, value) values ('MCG', 'Morphological Catalog of Galaxies');
INSERT INTO catalog_code(code, value) values ('Me', 'Merrill (plantary nebulae)');
INSERT INTO catalog_code(code, value) values ('Mrk', 'Markarian (open clusters and galaxies)');
INSERT INTO catalog_code(code, value) values ('Mel', 'Melotte (open clusters)');
INSERT INTO catalog_code(code, value) values ('M1', 'Minkowski (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('M2', 'Minkowski (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('M3', 'Minkowski (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('M4', 'Minkowski (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('New', '"New" galaxies in the Revised Shapley-Ames Catalog');
INSERT INTO catalog_code(code, value) values ('NGC', 'New General Catalog of Nebulae & Clusters of Stars');
INSERT INTO catalog_code(code, value) values ('Pal', 'Palomar (globular clusters)');
INSERT INTO catalog_code(code, value) values ('PB', 'Peimbert and Batiz (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('PC', 'Peimbert and Costero (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('Pismis', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('PK', 'Perek & Kohoutek (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('RCW', 'Rodgers, Campbell, & Whiteoak (bright nebulae)');
INSERT INTO catalog_code(code, value) values ('Roslund', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('Ru', 'Ruprecht (open clusters)');
INSERT INTO catalog_code(code, value) values ('Sa', 'Sandqvist (dark nebulae)');
INSERT INTO catalog_code(code, value) values ('Sher', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('Sh', 'Sharpless (bright nebulae)');
INSERT INTO catalog_code(code, value) values ('SL', 'Sandqvist & Lindroos (dark nebulae) or Shapley & Lindsay (clusters in LMC)');
INSERT INTO catalog_code(code, value) values ('Steph', 'Stephenson (open clusters)');
INSERT INTO catalog_code(code, value) values ('Stock', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('Ter', 'Terzan (globular clusters)');
INSERT INTO catalog_code(code, value) values ('Tombaugh', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('Ton', 'Tonantzintla (globular clusters)');
INSERT INTO catalog_code(code, value) values ('Tr', 'Trumpler (open clusters)');
INSERT INTO catalog_code(code, value) values ('UGC', 'Uppsala General Catalog (galaxies)');
INSERT INTO catalog_code(code, value) values ('UGCA', 'Uppsala General Catalog, Addendum (galaxies)');
INSERT INTO catalog_code(code, value) values ('UKS', 'United Kingdom Schmidt (globular clusters)');
INSERT INTO catalog_code(code, value) values ('Upgren', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('V V', 'Vorontsov-Velyaminov (interacting galaxies)');
INSERT INTO catalog_code(code, value) values ('vdB', 'Van den Bergh (open clusters, bright nebulae)');
INSERT INTO catalog_code(code, value) values ('vdBH', 'Van den Bergh & Herbst (bright nebulae)');
INSERT INTO catalog_code(code, value) values ('vdB-Ha', 'Van den Bergh-Hagen (open clusters)');
INSERT INTO catalog_code(code, value) values ('Vy', 'Vyssotsky (planetary nebulae)');
INSERT INTO catalog_code(code, value) values ('Waterloo', 'Open clusters');
INSERT INTO catalog_code(code, value) values ('Winnecke', 'Double Star (Messier 40)');
INSERT INTO catalog_code(code, value) values ('ZwG', 'Zwicky (galaxies)');
