DROP TABLE IF EXISTS constellation;

CREATE TABLE constellation (
	code VARCHAR(3) PRIMARY KEY,
	name VARCHAR(20) NOT NULL
) Engine=InnoDB;

INSERT INTO constellation (name, code) values('ANDROMEDA', 'AND');
INSERT INTO constellation (name, code) values('LACERTA', 'LAC');
INSERT INTO constellation (name, code) values('ANTLIA', 'ANT');
INSERT INTO constellation (name, code) values('LEO', 'LEO');
INSERT INTO constellation (name, code) values('APUS', 'APS');
INSERT INTO constellation (name, code) values('LEO MINOR', 'LMI');
INSERT INTO constellation (name, code) values('AQUARIUS', 'AQR');
INSERT INTO constellation (name, code) values('LEPUS', 'LEP');
INSERT INTO constellation (name, code) values('AQUILA', 'AQL');
INSERT INTO constellation (name, code) values('LIBRA', 'LIB');
INSERT INTO constellation (name, code) values('ARA', 'ARA');
INSERT INTO constellation (name, code) values('LUPUS', 'LUP');
INSERT INTO constellation (name, code) values('ARIES', 'ARI');
INSERT INTO constellation (name, code) values('LYNX', 'LYN');
INSERT INTO constellation (name, code) values('AURIGA', 'AUR');
INSERT INTO constellation (name, code) values('LYRA', 'LYR');
INSERT INTO constellation (name, code) values('BOOTES', 'BOO');
INSERT INTO constellation (name, code) values('MENSA', 'MEN');
INSERT INTO constellation (name, code) values('CAELUM', 'CAE');
INSERT INTO constellation (name, code) values('MICROSCOPIUM', 'MIC');
INSERT INTO constellation (name, code) values('CAMELOPARDALIS', 'CAM');
INSERT INTO constellation (name, code) values('MONOCEROS', 'MON');
INSERT INTO constellation (name, code) values('CANCER', 'CNC');
INSERT INTO constellation (name, code) values('MUSCA', 'MUS');
INSERT INTO constellation (name, code) values('CANES VENATICI', 'CVN');
INSERT INTO constellation (name, code) values('NORMA', 'NOR');
INSERT INTO constellation (name, code) values('CANIS MAJOR', 'CMA');
INSERT INTO constellation (name, code) values('OCTANS', 'OCT');
INSERT INTO constellation (name, code) values('CANIS MINOR', 'CMI');
INSERT INTO constellation (name, code) values('OPHIUCHUS', 'OPH');
INSERT INTO constellation (name, code) values('CAPRICORNUS', 'CAP');
INSERT INTO constellation (name, code) values('ORION', 'ORI');
INSERT INTO constellation (name, code) values('CARINA', 'CAR');
INSERT INTO constellation (name, code) values('PAVO', 'PAV');
INSERT INTO constellation (name, code) values('CASSIOPEIA', 'CAS');
INSERT INTO constellation (name, code) values('PEGASUS', 'PEG');
INSERT INTO constellation (name, code) values('CENTAURUS', 'CEN');
INSERT INTO constellation (name, code) values('PERSEUS', 'PER');
INSERT INTO constellation (name, code) values('CEPHEUS', 'CEP');
INSERT INTO constellation (name, code) values('PHOENIX', 'PHE');
INSERT INTO constellation (name, code) values('CETUS', 'CET');
INSERT INTO constellation (name, code) values('PICTOR', 'PIC');
INSERT INTO constellation (name, code) values('CHAMAELEON', 'CHA');
INSERT INTO constellation (name, code) values('PISCES', 'PSC');
INSERT INTO constellation (name, code) values('CIRCINUS', 'CIR');
INSERT INTO constellation (name, code) values('PISCES AUSTRINUS', 'PSA');
INSERT INTO constellation (name, code) values('COLUMBA', 'COL');
INSERT INTO constellation (name, code) values('PUPPIS', 'PUP');
INSERT INTO constellation (name, code) values('COMA BERENICES', 'COM');
INSERT INTO constellation (name, code) values('PYXIS', 'PYX');
INSERT INTO constellation (name, code) values('CORONA AUSTRALIS', 'CRA');
INSERT INTO constellation (name, code) values('RETICULUM', 'RET');
INSERT INTO constellation (name, code) values('CORONA BOREALIS', 'CRB');
INSERT INTO constellation (name, code) values('SAGITTA', 'SGE');
INSERT INTO constellation (name, code) values('CORVUS', 'CRV');
INSERT INTO constellation (name, code) values('SAGITTARIUS', 'SGR');
INSERT INTO constellation (name, code) values('CRATER', 'CRT');
INSERT INTO constellation (name, code) values('SCORPIUS', 'SCO');
INSERT INTO constellation (name, code) values('CRUX', 'CRU');
INSERT INTO constellation (name, code) values('SCULPTOR', 'SCL');
INSERT INTO constellation (name, code) values('CYGNUS', 'CYG');
INSERT INTO constellation (name, code) values('SCUTUM', 'SCT');
INSERT INTO constellation (name, code) values('DELPHINUS', 'DEL');
INSERT INTO constellation (name, code) values('SERPENS', 'SER');
INSERT INTO constellation (name, code) values('DORADO', 'DOR');
INSERT INTO constellation (name, code) values('SEXTANS', 'SEX');
INSERT INTO constellation (name, code) values('DRACO', 'DRA');
INSERT INTO constellation (name, code) values('TAURUS', 'TAU');
INSERT INTO constellation (name, code) values('EQUULEUS', 'EQU');
INSERT INTO constellation (name, code) values('TELESCOPIUM', 'TEL');
INSERT INTO constellation (name, code) values('ERIDANUS', 'ERI');
INSERT INTO constellation (name, code) values('TRIANGULUM AUSTRALE', 'TRA');
INSERT INTO constellation (name, code) values('FORNAX', 'FOR');
INSERT INTO constellation (name, code) values('TRIANGULUM', 'TRI');
INSERT INTO constellation (name, code) values('GEMINI', 'GEM');
INSERT INTO constellation (name, code) values('TUCANA', 'TUC');
INSERT INTO constellation (name, code) values('GRUS', 'GRU');
INSERT INTO constellation (name, code) values('URSA MAJOR', 'UMA');
INSERT INTO constellation (name, code) values('HERCULES', 'HER');
INSERT INTO constellation (name, code) values('URSA MINOR', 'UMI');
INSERT INTO constellation (name, code) values('HOROLOGIUM', 'HOR');
INSERT INTO constellation (name, code) values('VELA', 'VEL');
INSERT INTO constellation (name, code) values('HYDRA', 'HYA');
INSERT INTO constellation (name, code) values('VIRGO', 'VIR');
INSERT INTO constellation (name, code) values('HYDRUS', 'HYI');
INSERT INTO constellation (name, code) values('VOLANS', 'VOL');
INSERT INTO constellation (name, code) values('INDUS', 'IND');
INSERT INTO constellation (name, code) values('VULPECULA', 'VUL');